version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: notchr_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: notchr_backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notchr-jobs
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: notchr_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data: